services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: naveen
      POSTGRES_PASSWORD: naveen123
      POSTGRES_DB: hotelDB
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
